# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwift_MVVM_Practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwift_MVVM_Practice

	pod 'RxSwift'
  	pod 'RxCocoa'
  	pod 'RxRelay'
  	pod 'RxOptional'
  	pod 'RxViewController'
        pod 'SnapKit'

  target 'RxSwift_MVVM_PracticeTests' do
    inherit! :search_paths
    # Pods for testing
	pod 'RxTest'
   	pod 'RxBlocking'
  end

  target 'RxSwift_MVVM_PracticeUITests' do
    # Pods for testing
  end

end
